---
- hosts: localhost
  tasks:
    - name: simple debug
      debug:
        msg: "anil"
    - name: simple variable debug
      debug:
        var: my_variable
    - name: simple debug
      debug:
        msg: "{{ my_variable }}"
