- name: simple debug
  debug:
    msg: "anil"
- name: simple variable debug
  debug:
    var: my_variable
- name: simple debug
  debug:
    msg: " The current value of variable is {{ my_variable }}"
- name: create directory
  file:
   path: /home/devopsadmin/anil
   state: directory
  register: dir_out
- name: simple debug
  debug:
    msg: dir_out

